package com.raven.api.resources.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.raven.api.resources.types.BatchEvent;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(
    builder = BulkSendEventRequest.Builder.class
)
public final class BulkSendEventRequest {
  private final Optional<String> idempotencyKey;

  private final String event;

  private final List<BatchEvent> batch;

  private int _cachedHashCode;

  BulkSendEventRequest(Optional<String> idempotencyKey, String event, List<BatchEvent> batch) {
    this.idempotencyKey = idempotencyKey;
    this.event = event;
    this.batch = batch;
  }

  /**
   * @return The API supports idempotency for safely retrying requests without accidentally performing the same operation twice.
   * This is useful when an API call is disrupted in transit and you do not receive a response.
   * For example, if a request to send event does not respond due to a network connection error, you can retry the request with the same idempotency key to guarantee that no more than one event is sent.
   * An idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request.
   * How you create unique keys is up to you, but we suggest using V4 UUIDs, or another random string with enough entropy to avoid collisions.
   * Idempotency keys can be up to 255 characters long.
   */
  @JsonProperty("Idempotency-Key")
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  @JsonProperty("event")
  public String getEvent() {
    return event;
  }

  /**
   * @return List of events
   */
  @JsonProperty("batch")
  public List<BatchEvent> getBatch() {
    return batch;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkSendEventRequest && equalTo((BulkSendEventRequest) other);
  }

  private boolean equalTo(BulkSendEventRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && event.equals(other.event) && batch.equals(other.batch);
  }

  @Override
  public int hashCode() {
    if (_cachedHashCode == 0) {
      _cachedHashCode = Objects.hash(this.idempotencyKey, this.event, this.batch);
    }
    return _cachedHashCode;
  }

  @Override
  public String toString() {
    return "BulkSendEventRequest{" + "idempotencyKey: " + idempotencyKey + ", event: " + event + ", batch: " + batch + "}";
  }

  public static EventStage builder() {
    return new Builder();
  }

  public interface EventStage {
    _FinalStage event(String event);

    Builder from(BulkSendEventRequest other);
  }

  public interface _FinalStage {
    BulkSendEventRequest build();

    _FinalStage idempotencyKey(Optional<String> idempotencyKey);

    _FinalStage idempotencyKey(String idempotencyKey);

    _FinalStage batch(List<BatchEvent> batch);

    _FinalStage addBatch(BatchEvent batch);

    _FinalStage addAllBatch(List<BatchEvent> batch);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EventStage, _FinalStage {
    private String event;

    private List<BatchEvent> batch = new ArrayList<>();

    private Optional<String> idempotencyKey = Optional.empty();

    private Builder() {
    }

    @Override
    public Builder from(BulkSendEventRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      event(other.getEvent());
      batch(other.getBatch());
      return this;
    }

    @Override
    @JsonSetter("event")
    public _FinalStage event(String event) {
      this.event = event;
      return this;
    }

    /**
     * <p>List of events</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage addAllBatch(List<BatchEvent> batch) {
      this.batch.addAll(batch);
      return this;
    }

    /**
     * <p>List of events</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage addBatch(BatchEvent batch) {
      this.batch.add(batch);
      return this;
    }

    @Override
    @JsonSetter(
        value = "batch",
        nulls = Nulls.SKIP
    )
    public _FinalStage batch(List<BatchEvent> batch) {
      this.batch.clear();
      this.batch.addAll(batch);
      return this;
    }

    /**
     * <p>The API supports idempotency for safely retrying requests without accidentally performing the same operation twice.
     * This is useful when an API call is disrupted in transit and you do not receive a response.
     * For example, if a request to send event does not respond due to a network connection error, you can retry the request with the same idempotency key to guarantee that no more than one event is sent.
     * An idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request.
     * How you create unique keys is up to you, but we suggest using V4 UUIDs, or another random string with enough entropy to avoid collisions.
     * Idempotency keys can be up to 255 characters long.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.of(idempotencyKey);
      return this;
    }

    @Override
    @JsonSetter(
        value = "Idempotency-Key",
        nulls = Nulls.SKIP
    )
    public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    @Override
    public BulkSendEventRequest build() {
      return new BulkSendEventRequest(idempotencyKey, event, batch);
    }
  }
}
