package com.raven.api.client.event.endpoints;

import com.raven.api.client.Authorization;
import com.raven.api.client.event.types.SendEventRequest;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public final class Send {
  private Send() {
  }

  public static final class Request {
    private final Optional<String> idempotencyKey;

    private final String appId;

    private final SendEventRequest body;

    private final Optional<Authorization> authOverride;

    private int _cachedHashCode;

    Request(Optional<String> idempotencyKey, String appId, SendEventRequest body,
        Optional<Authorization> authOverride) {
      this.idempotencyKey = idempotencyKey;
      this.appId = appId;
      this.body = body;
      this.authOverride = authOverride;
    }

    /**
     * @return The API supports idempotency for safely retrying requests without accidentally performing the same operation twice.
     * This is useful when an API call is disrupted in transit and you do not receive a response.
     * For example, if a request to send event does not respond due to a network connection error, you can retry the request with the same idempotency key to guarantee that no more than one event is sent.
     * An idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request.
     * How you create unique keys is up to you, but we suggest using V4 UUIDs, or another random string with enough entropy to avoid collisions.
     * Idempotency keys can be up to 255 characters long.
     */
    public Optional<String> getIdempotencyKey() {
      return idempotencyKey;
    }

    public String getAppId() {
      return appId;
    }

    public SendEventRequest getBody() {
      return body;
    }

    public Optional<Authorization> getAuthOverride() {
      return authOverride;
    }

    @Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof Request && equalTo((Request) other);
    }

    private boolean equalTo(Request other) {
      return idempotencyKey.equals(other.idempotencyKey) && appId.equals(other.appId) && body.equals(other.body) && authOverride.equals(other.authOverride);
    }

    @Override
    public int hashCode() {
      if (_cachedHashCode == 0) {
        _cachedHashCode = Objects.hash(this.idempotencyKey, this.appId, this.body, this.authOverride);
      }
      return _cachedHashCode;
    }

    @Override
    public String toString() {
      return "Send.Request{" + "idempotencyKey: " + idempotencyKey + ", appId: " + appId + ", body: " + body + ", authOverride: " + authOverride + "}";
    }

    public static AppIdStage builder() {
      return new Builder();
    }

    public interface AppIdStage {
      BodyStage appId(String appId);

      Builder from(Request other);
    }

    public interface BodyStage {
      _FinalStage body(SendEventRequest body);
    }

    public interface _FinalStage {
      Request build();

      _FinalStage idempotencyKey(Optional<String> idempotencyKey);

      _FinalStage idempotencyKey(String idempotencyKey);

      _FinalStage authOverride(Optional<Authorization> authOverride);

      _FinalStage authOverride(Authorization authOverride);
    }

    public static final class Builder implements AppIdStage, BodyStage, _FinalStage {
      private String appId;

      private SendEventRequest body;

      private Optional<Authorization> authOverride = Optional.empty();

      private Optional<String> idempotencyKey = Optional.empty();

      private Builder() {
      }

      @Override
      public Builder from(Request other) {
        idempotencyKey(other.getIdempotencyKey());
        appId(other.getAppId());
        body(other.getBody());
        authOverride(other.getAuthOverride());
        return this;
      }

      @Override
      public BodyStage appId(String appId) {
        this.appId = appId;
        return this;
      }

      @Override
      public _FinalStage body(SendEventRequest body) {
        this.body = body;
        return this;
      }

      @Override
      public _FinalStage authOverride(Authorization authOverride) {
        this.authOverride = Optional.of(authOverride);
        return this;
      }

      @Override
      public _FinalStage authOverride(Optional<Authorization> authOverride) {
        this.authOverride = authOverride;
        return this;
      }

      /**
       * <p>The API supports idempotency for safely retrying requests without accidentally performing the same operation twice.
       * This is useful when an API call is disrupted in transit and you do not receive a response.
       * For example, if a request to send event does not respond due to a network connection error, you can retry the request with the same idempotency key to guarantee that no more than one event is sent.
       * An idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request.
       * How you create unique keys is up to you, but we suggest using V4 UUIDs, or another random string with enough entropy to avoid collisions.
       * Idempotency keys can be up to 255 characters long.</p>
       * @return Reference to {@code this} so that method calls can be chained together.
       */
      @Override
      public _FinalStage idempotencyKey(String idempotencyKey) {
        this.idempotencyKey = Optional.of(idempotencyKey);
        return this;
      }

      @Override
      public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
      }

      @Override
      public Request build() {
        return new Request(idempotencyKey, appId, body, authOverride);
      }
    }
  }
}
